In [ ]:
import pandas as pd
import numpy as np

import seaborn as sns #타이타닉 데이터가 들어있는 패키지

In [ ]:
tt=sns.load_dataset('titanic') #tt: 타이타닉 데이터셋

In [ ]:
# shape (행, 열) 확인
tt.shape
tt.shape[0]

891

In [ ]:
# columns 컬럼만 보여줌
tt_col=tt.columns
tt_col

Index(['survived', 'pclass', 'sex', 'age', 'sibsp', 'parch', 'fare',
       'embarked', 'class', 'who', 'adult_male', 'deck', 'embark_town',
       'alive', 'alone'],
      dtype='object')

In [ ]:
# info() 기본 정보 제공
tt.info()

# dtypes 컬럼들의 타입 보여줌
tt.dtypes

# describe() 기초통계값 (평균, 최대, 최소 등)
tt.describe()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 15 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   survived     891 non-null    int64
 1   pclass       891 non-null    int64
 2   sex          891 non-null    object
 3   age          714 non-null    float64
 4   sibsp        891 non-null    int64
 5   parch        891 non-null    int64
 6   fare         891 non-null    float64
 7   embarked     889 non-null    object
 8   class        891 non-null    category
 9   who          891 non-null    object
 10  adult_male   891 non-null    bool
 11  deck         203 non-null    category
 12  embark_town  889 non-null    object
 13  alive        891 non-null    object
 14  alone        891 non-null    bool
dtypes: bool(2), category(2), float64(2), int64(4), object(5)
memory usage: 80.7+ KB

         survived      pclass         age       sibsp       parch        fare
count  891.000000  891.000000  714.000000  891.000000  891.000000  891.000000
mean     0.383838    2.308642   29.699118    0.523008    0.381594   32.204208
std      0.486592    0.836071   14.526497    1.102743    0.806057   49.693429
min      0.000000    1.000000    0.420000    0.000000    0.000000    0.000000
25%      0.000000    2.000000   20.125000    0.000000    0.000000    7.910400
50%      0.000000    3.000000   28.000000    0.000000    0.000000   14.454200
75%      1.000000    3.000000   38.000000    1.000000    0.000000   31.000000
max      1.000000    3.000000   80.000000    8.000000    6.000000  512.329200

In [ ]:
# head() 앞 5개 열 데이터 제공
tt.head()

# tail() 뒤 5개 열 데이터 제
tt.tail()

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alive,alone
886,0,2,male,27.0,0,0,13.00,S,Second,man,True,NaN,Southampton,no,True
887,1,1,female,19.0,0,0,30.00,S,First,woman,False,B,Southampton,yes,True
888,0,3,female,NaN,1,2,23.45,S,Third,woman,False,NaN,Southampton,no,False
889,1,1,male,26.0,0,0,30.00,C,First,man,True,C,Cherbourg,yes,True
890,0,3,male,32.0,0,0,7.75,Q,Third,man,True,NaN,Queenstown,no,True

## **행과 열로 접근하여 데이터 추출하기**

In [ ]:
# 열을 통한 접근
tt['survived'] #1차원 배열
tt[['survived', 'pclass']] #2차원 배열

In [ ]:
# 행을 통한 접근
# loc: 행 인덱스 기준으로 추출
#     -1로 끝값 접근 불가
# iloc: 추출한 인덱스 기준
#     -1로 끝값 접근 가능


# 5행의 모든 데이터값 출력
tt.loc[5]
tt.iloc[5]

survived                0
pclass                  3
sex                  male
age                   NaN
sibsp                   0
parch                   0
fare               8.4583
embarked                Q
class               Third
who                   man
adult_male           True
deck                  NaN
embark_town    Queenstown
alive                  no
alone                True
Name: 5, dtype: object

In [ ]:
num_row=tt.shape[0] #행의 수
last_index=num_row-1 #행의 수 -1 => 가장 마지막 행
tt.loc[last_index] #가장 마지막 데이터 추출

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alive,alone
890,0,3,male,32.0,0,0,7.75,Q,Third,man,True,NaN,Queenstown,no,True

In [ ]:
#원하는 행만 숫자로 추출 가능
tt.loc[[0, 2, 3,6, 880]]
tt.iloc[[0, 2, 3,6, 880]] #데이터를 자르지 않았으므로 iloc도 값 동일

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alive,alone
0,0,3,male,22.0,1,0,7.2500,S,Third,man,True,NaN,Southampton,no,False
2,1,3,female,26.0,0,0,7.9250,S,Third,woman,False,NaN,Southampton,yes,True
3,1,1,female,35.0,1,0,53.1000,S,First,woman,False,C,Southampton,yes,False
6,0,1,male,54.0,0,0,51.8625,S,First,man,True,E,Southampton,no,True
880,1,2,female,25.0,0,1,26.0000,S,Second,woman,False,NaN,Southampton,yes,False

In [ ]:
#10부터 150까지 데이터를 2 간격으로
tt.loc[10:150:2]
tt.iloc[10:150:2]

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alive,alone
10,1,3,female,4.0,1,1,16.7000,S,Third,child,False,G,Southampton,yes,False
12,0,3,male,20.0,0,0,8.0500,S,Third,man,True,NaN,Southampton,no,True
14,0,3,female,14.0,0,0,7.8542,S,Third,child,False,NaN,Southampton,no,True
16,0,3,male,2.0,4,1,29.1250,Q,Third,child,False,NaN,Queenstown,no,False
18,0,3,female,31.0,1,0,18.0000,S,Third,woman,False,NaN,Southampton,no,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
140,0,3,female,NaN,0,2,15.2458,C,Third,woman,False,NaN,Cherbourg,no,False
142,1,3,female,24.0,1,0,15.8500,S,Third,woman,False,NaN,Southampton,yes,False
144,0,2,male,18.0,0,0,11.5000,S,Second,man,True,NaN,Southampton,no,True
146,1,3,male,27.0,0,0,7.7958,S,Third,man,True,NaN,Southampton,yes,True
148,0,2,male,36.5,0,2,26.0000,S,Second,man,True,F,Southampton,no,False

In [ ]:
# loc과 iloc의 차이 중 하나: 컬럼 접근
# iloc: 컬럼을 숫자로만 접근 가능
# loc: 컬럼 이름으로 접근 가능
# ex) tt.loc[행, 열]

tt.loc[::2, ['age', 'survived']] #::2가 행 관련, ['age']가 열관련

      age  survived
0    22.0         0
2    26.0         1
4    35.0         0
6    54.0         0
8    27.0         1
..    ...       ...
882  22.0         0
884  25.0         0
886  27.0         0
888   NaN         0
890  32.0         0

[446 rows x 2 columns]

# **기초 통계값 사용**

In [ ]:
# 기초 통계

# 평균
tt['fare'].mean() #판다스 사용
np.mean(tt['fare']) #넘파이 사용

# 합
tt['fare'].sum()
np.sum(tt['fare'])

# 중간값
tt['fare'].median()
np.median(tt['fare'])

# 최댓값
tt['fare'].argmax()
np.argmax(tt['fare'])

# 최솟값
tt['fare'].argmin()
np.argmin(tt['fare'])

179

In [ ]:
# groupby('그룹을 묶을 컬럼')['통계치를 볼 컬럼'] 그룹별로 묶음
tt.groupby('pclass')['fare', 'age'].mean()

<ipython-input-29-c79b1d54c868>:3: FutureWarning: Indexing with multiple keys (implicitly converted to a tuple of keys) will be deprecated, use a list instead.
  tt.groupby('pclass')['fare', 'age'].mean()

             fare        age
pclass
1       84.154687  38.233441
2       20.662183  29.877630
3       13.675550  25.140620

In [ ]:
# 접근 순서

# 열 -> 행
tt[['survived', 'class']].loc[2: 40]

# 행 -> 열
tt.loc[2: 40][['survived', 'class']]

    survived   class
2          1   Third
3          1   First
4          0   Third
5          0   Third
6          0   First
7          0   Third
8          1   Third
9          1  Second
10         1   Third
11         1   First
12         0   Third
13         0   Third
14         0   Third
15         1  Second
16         0   Third
17         1  Second
18         0   Third
19         1   Third
20         0  Second
21         1  Second
22         1   Third
23         1   First
24         0   Third
25         1   Third
26         0   Third
27         0   First
28         1   Third
29         0   Third
30         0   First
31         1   First
32         1   Third
33         0  Second
34         0   First
35         0   First
36         1   Third
37         0   Third
38         0   Third
39         1   Third
40         0   Third

**기타 기초 문법**
*   query()
*   sort_values()
*   groupby()
*   assign(), lambda
*   agg()
*   merge()
*   concat()
*   str()
*   시계열

In [ ]:
# query('요구조건') 데이터 추출 조건
# 논리 연산자 and or 사용 가능


# embark가 S인 데이터 접근
tt.query('''embarked == "S" ''')

# 수치형 데이터 fare 접근
tt.query("fare > 32")

#S가 아니고 요금 90 초과 승객이나 나이가 10살 미만인 승객의 생존률의 평균
tt.query(''' embarked != "S" and fare > 90 or age < 10''')['survived'].mean()

0.6559139784946236